## Numpy

In [1]:
import numpy as np

In [3]:
v = np.array([1, 2, 3, 4])  # Аргумент для array() - питоновский обычный список для создания вектора
v

array([1, 2, 3, 4])

In [14]:
M = np.array([[1, 2], [3, 4]])  # Аргумент для array() - питоновский вложенный список для создания матрицы
M

array([[1, 2],
       [3, 4]])

In [15]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [16]:
v.shape  # Без круглых скобок

(4,)

In [17]:
# Посмотреть форму массива:
M.shape

(2, 2)

In [18]:
# Посчитать количество элементов в массиве:
np.size(M)

4

In [19]:
# К какому типу данных относится наш массив/ матрица:
M.dtype

dtype('int32')

In [20]:
# Каждый массив имеет только один заранее определенный тип данных. Не может быть массива с разными типами данных:

M[0, 0] = 'Hello'

ValueError: invalid literal for int() with base 10: 'Hello'

In [21]:
M = np.array([[1, 2], [3, 4]], dtype = complex)  # Хотим создать массив из компексных чисел
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

__Основные типы данных в массиве:__ int, float, bool, complex

### Функции генерации массивов

In [24]:
# Функции генерации массивов:
x = np.arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

__1. arange(start, stop, step)__

In [28]:
x = np.arange(-1, 1, 0.1)  # В питоне нельзя делать список из дробных элементов, а в numpy можно
x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

__2. linspace__ создает последовательность данных, равномерно расположенных на числовой прямой в заданном интервале. В отличие от arange обе точки включаются в массив.

In [27]:
np.linspace(0, 10, 25)
# От 0 до 10 включительно. 25 - это количество значений.
# Это удобно для построения графиков, расчета промежутков интервалов времени и т.д.

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

__3. logspace__ возвращает последовательность данных, которая равномерно расположена на числовой прямой, но в логарифмическом масштабе.

In [29]:
np.logspace(0, 10, 10, base = np.e)
# Можно указать по какому основанию, например, по экспоненте: base = np.e

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

### Матрицы

__numpy mgrid__ создает 2d массив с аналогичными значениями. Это сетка многомерных массивов одной размерности. Удобно, например, когда создаем координаты.

In [30]:
np.mgrid[0:5, 0:5]
x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [31]:
x, y = np.mgrid[0:5, 0:5]

In [32]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [33]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

__Рандомные матрицы__

In [36]:
np.random.rand(5, 5)

array([[0.68524303, 0.53513985, 0.33330772, 0.85309752, 0.31034416],
       [0.43369326, 0.16161783, 0.07375681, 0.12037625, 0.07840613],
       [0.16995753, 0.40603352, 0.66485159, 0.74772844, 0.23374894],
       [0.29086562, 0.18330564, 0.85766002, 0.74957129, 0.90386916],
       [0.54114909, 0.25787179, 0.36670711, 0.70299241, 0.4415119 ]])

In [39]:
np.random.randn(5, 5)  # Нормальное распределение

array([[ 1.35296578,  0.70766581,  0.62579039, -1.09350925,  1.26143152],
       [ 0.25438493,  0.40401628, -1.24993755,  0.93949994,  0.52758389],
       [-2.1413021 , -2.28785761, -0.58933508,  0.00797381,  0.17252987],
       [ 0.89632855, -0.00491905, -1.53088245,  0.10062333,  0.83153675],
       [ 0.09651718,  0.90311854,  0.6142559 , -0.98182781,  0.77725726]])

__Диагональная матрица__

In [43]:
np.diag([1, 2, 3, 4, 5, 6, 7])  # Аргумент для np.diag - это значения, которые будут по диагонали
                                # Остальная часть матрицы заполнена нулями. Это квадратная матрица

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

Диагональная матрица с отступом: аргумент k

In [45]:
np.diag([1, 2, 3, 4, 5, 6, 7], k = 1)
# Появится пустой ряд и пустой столбец

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 7],
       [0, 0, 0, 0, 0, 0, 0, 0]])

__Матрицы, заполненные нулями__  
__Матрицы, заполненные единицами__

In [46]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.ones((3, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])